### ISSUE TITLE
Impedance Measurement

### ISSUE THREAD

**Issue by FarnoodF** [OpenBCI/brainflow#160]
I need to access each channel's impedance throughout the experiment and I do not find this functionality in BrainFlow. Do you think it's something to be added soon?

**Comment by Andrey1994** [comment]
For ganglion its available: https://github.com/OpenBCI/brainflow/blob/master/tests/python/ganglion_resist.py 
For cyton you can do it in user code but it requires more efforts, take a loot at these links: https://github.com/OpenBCI/OpenBCI_GUI/blob/master/OpenBCI_GUI/BoardCyton.pde#L371 https://docs.openbci.com/docs/02Cyton/CytonSDK#leadoff-impedance-commands 

And devices dont support getting EEG and Impedance values at the same time...

**Comment by Andrey1994** [comment]
For ganglion its available: https://github.com/OpenBCI/brainflow/blob/master/tests/python/ganglion_resist.py 
For cyton you can do it in user code but it requires more efforts, take a loot at these links: https://github.com/OpenBCI/OpenBCI_GUI/blob/master/OpenBCI_GUI/BoardCyton.pde#L371 https://docs.openbci.com/docs/02Cyton/CytonSDK#leadoff-impedance-commands 

And devices dont support getting EEG and Impedance values at the same time...

**Comment by Andrey1994** [comment]
and for cyton impedance values are in EEG channels.

I do not have plans to provide Cyton speciffic API for it. You can use openbci gui to check impedance values before your experiment
