### ISSUE TITLE
get_sampling_rate returns the wrong value for cyton wifi in matlab

### ISSUE THREAD

**Issue by jacobgmartin** [OpenBCI/brainflow#161]
I can verify in the brainflow.log in matlab that the setting was correct at 1000hz.

I can also verify by sending board_shim.config_board('~~'), which also writes the correct sample rate to the log at 1000hz.

However, board_shim.get_sampling_rate(0) returns 250 no matter what I set the sampling rate to.

I've only tried matlab and cyton wifi.

**Comment by Andrey1994** [comment]
This method returns default sampling rate by design. Its not a bug

**Comment by Andrey1994** [comment]
And for cyton wifi board id is not 0, check docs
