### ISSUE TITLE
error: assertion failure

### ISSUE THREAD

**Issue by nosa999** [OpenBCI/brainflow#162]
Hi, I am trying to modify openBCI-GUI to add my custom device (like ganglion). I added my codes in files of ganglion in Brainflow for adding my device, and I started streaming data and I showed it in OpenBCI-GUI but the following error is occured.

![image](https://user-images.githubusercontent.com/40929193/95009981-cf3dd700-0632-11eb-8ecf-bb6e9d9f2683.png)

![image](https://user-images.githubusercontent.com/40929193/95010183-298b6780-0634-11eb-848d-86cba31fa87a.png)

**Comment by Andrey1994** [comment]
Try to run simple examples from brainflow docs using your device first and confirm that everything is correct.  You can also send PR to add your board to brainflow to https://github.com/brainflow-dev/brainflow and I will review your code

**Comment by Andrey1994** [comment]
Make sure that you follow these steps https://brainflow.readthedocs.io/en/stable/BrainFlowDev.html#instructions-to-add-new-boards-to-brainflow and feel free to ask further questions in slack
