### ISSUE TITLE
Chaning Baud Rate from BrainFlow python

### ISSUE THREAD

**Issue by FarnoodF** [OpenBCI/brainflow#163]
Is there any way to change the baud rate from brainflow?

**Comment by Andrey1994** [comment]
No because its implementation detail for specific board and no need to change it. If you are working on your own boards or custom version of Cyton you can use another baud rate in brainflow's code. But it will not be added to the user API

**Comment by FarnoodF** [comment]
I'm using a custom version of Cyton, could you show me how to "use another baud rate in brainflow's code"?

**Comment by Andrey1994** [comment]
for windows https://github.com/brainflow-dev/brainflow/blob/master/src/utils/serial.cpp#L50 
for linux https://github.com/brainflow-dev/brainflow/blob/master/src/utils/serial.cpp#L50 and https://github.com/brainflow-dev/brainflow/blob/master/src/utils/serial.cpp#L132 

after that rebuild it and install required binding from local folder. Check docs for instructions
