### ISSUE TITLE
is available brainflow jniLibs & jar for Android serial connection?

### ISSUE THREAD

**Issue by gyanr0425** [OpenBCI/brainflow#164]
Hello, @Andrey1994 

I am writing to inquire about implementation of serial connection with Android application,
using Galaxy S20 (SM-G986B) on Android 10 and Cyton board (8 channel) of openBCI.
[ Android phone - (otg cable) - dongle  ~ Cyton board ]

```
public OpenBCIReader(int board_id, String serial_port)

reader = new OpenBCIReader(0, "/dev/ttySAC1");

reader.open_session();
reader.get_data();
reader.close_session();
```
The codes are very simple test with sample codes for trying to connect the phone (connected dongle) with Cyton.
I defined a class OpenBCIReader which have methods like open_session(), get_data(), close_session() simply.
Now, there are not any errors, but it shows no data string from the board.
( the result of board_shim.get_board_data_count() is 0. )

So, I am wondering that these items are possible with the release version.
- Could an application with jniLibs which you provided link to c++ codes (built in .so files) on Android system
  in the part of the below code?
> instance = (DllInterface) Native.loadLibrary (lib_name, DllInterface.class);
  Following guides of documentation, I placed .jar file and jniLibs folder (unzipped) on the right path.

- Second, could it connect with cyton board without any external driver using Android API?
  I am thinking about whether I really don't need Android API like android.hardware.usb to probe and connect with host (dongle).
  
Unfortunately, I cannot debug because I have to connect the dongle with phone when testing.

**Comment by Andrey1994** [comment]
Hello,

First of all I dont understand what it is and how its related to BrainFlow
```
public OpenBCIReader(int board_id, String serial_port)

reader = new OpenBCIReader(0, "/dev/ttySAC1");

reader.open_session();
reader.get_data();
reader.close_session();
```

I also dont fully understand this question. Do you mean https://github.com/brainflow-dev/BrainFlowAndroidTest ? 
"Could an application with jniLibs which you provided link to c++ codes (built in .so files) on Android system
in the part of the below code?"

"Second, could it connect with cyton board without any external driver using Android API?"
Do you mean smth like ftdi drivers for Android?

Right now Cyton wo wifi shield is not officially supported on Android, mostly because I have not tested it.

**Comment by gyanr0425** [comment]
Sorry for confusing you.
OpenBCIReader is just my custom class 
which contains..
BoardShim board_shim = new BoardShim (board_id, params);
board_shim.prepare_session()
board_shim.start_stream()
board_shim.stop_stream()
and board_shim.release_session()
to print out data from Cyton board in TextView of my app
using brainflow library Java APIs in each method by function.

I don’t mean that BrainflowAndroidTest repo with requirements for WiFi shield because I want to use only serial connection with dongle.

“Do you mean smth like ftdi drivers for Android?”
-> Yes, right.
  I saw serial.cpp, board_controller.cpp, etc. (in src folder) that seems to be needed for serial communication, and thought that I could open session and connect. However, I couldn’t do that even with Synthetic board as well as real Cyton board.

 As you said, if Cyton w/o wifi shield is not officially supported, could I get additional guides for this problem..?

**Comment by Andrey1994** [comment]
" However, I couldn’t do that even with Synthetic board as well as real Cyton board."
Synthetic board works for sure, if it doesnt work for you it means a mistake in setup\code. Take a look at test app.

IDK how ftdi works on android but I assume driver is required. Or maybe its preinstalled.
Code from  serial.cpp, board_controller.cpp, etc is inside jniLibs, you can get latest libraries from https://github.com/brainflow-dev/brainflow/releases/tag/3.5.0 and take a look at https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#id1 

"couldn’t I get additional guides for this problem..?"
I have not tested it and dont know what can be wrong(maybe it just works), but I guess some more actions required to run it. For example - special permissions, ftdi driver installation, etc

**Comment by Andrey1994** [comment]
Hod did you determine port name on Android?
I mean this `reader = new OpenBCIReader(0, "/dev/ttySAC1");`

**Comment by gyanr0425** [comment]
“ Synthetic board works for sure, if it doesnt work for you it means a mistake in setup\code. Take a look at test app.”
> Okay, synthetic board should work as I think, I will check it again.

“you can get latest libraries from ...”
> Yes, I already downloaded those files and I applied in my app. I will also look into if FTDI driver is required or pre-installed more.

Thank you for your detail replies,
and I look forward that shortly Brainflow support cyton board with usb serial connection via dongle officially.

**Comment by gyanr0425** [comment]
> Hod did you determine port name on Android?
> I mean this `reader = new OpenBCIReader(0, "/dev/ttySAC1");`

I am using cyton board on Ubuntu 16.04 and Windows 10, IK it works via ‘/dev/ttyUSB0’ and ‘COM9’ each. So, for Android, I searched which port is usually used and find out that ‘/dev/ttyS0’ similar to Linux. 

https://stackoverflow.com/questions/11011515/how-to-read-and-write-data-to-com-serial-ports-in-android

However, it would be changed as Android version was upgraded or could be different by users. In my case, I checked the path (/dev) and found which port’s folder had been changed recently in directory information after putting the dongle in my phone via adb shell. There are 4~5 ports such as ttyGS0, ttyGS8, ttyHS0 and ttySAC1 and out of them, ttySAC1 was picked up (also ‘bluetooth’ was owner of it). In addition, using chmod, permissions of those tty* folders for rwx was granted [su chmod 777 /dev/tty*]

**Comment by Andrey1994** [comment]
I have galaxy s9+ and for me usb port is /dev/ttyUSB0 exactly like on Android. I've installed app termux and run ls /dev/ with and wo dongle

**Comment by Andrey1994** [comment]
I see these ports "There are 4~5 ports such as ttyGS0, ttyGS8, ttyHS0 and ttySAC1 and out of them, ttySAC1" even wo connected dongle, so it makes me thing that you selected wrong port

**Comment by Andrey1994** [comment]
It doesnt work for me and idk how to debug it since I can not connect device to PC and use Cyton dongle at the same time.
I believe correct port name is /dev/ttyUSB0, I used these permissions
```
    <uses-feature android:name="android.hardware.usb.host"></uses-feature>
    <uses-permission android:name="android.permission.INTERNET"></uses-permission>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"></uses-permission>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"></uses-permission>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"></uses-permission>
    <uses-permission android:name="com.google.android.things.permission.USE_PERIPHERAL_IO"></uses-permission>
    <uses-permission android:name="android.permission.MANAGE_USB"
        tools:ignore="ProtectedPermissions"></uses-permission>
    <uses-permission android:name="android.permission.USB_PERMISSION"></uses-permission>
```

you can try
```
chmod 777 /dev/ttyUSB0
```
I didnt because I have no root at my phone

**Comment by Andrey1994** [comment]
I have some logs
```
2020-10-30 01:46:26.588 25951-25951/? I/brainflow_ndk_logger: [2020-10-30 01:46:26.588] [brainflow_logger] [info] incomming json: {"file":"","ip_address":"","ip_port":0,"ip_protocol":0,"mac_address":"","other_info":"","serial_number":"","serial_port":"/dev/ttyUSB0","timeout":0}
2020-10-30 01:46:26.589 25951-25951/? I/brainflow_ndk_logger: [2020-10-30 01:46:26.589] [brainflow_logger] [info] openning port /dev/ttyUSB0
2020-10-30 01:46:26.590 25951-25951/? E/BrainFlowLog: Error in prepare_session:UNABLE_TO_OPEN_PORT_ERROR"
```
it fails to open the port, for android it runs exactly the same code as for linux\macos. So there are two cases - other permissions needed(I think its a case) or for android code should be different(currently it does this https://github.com/brainflow-dev/brainflow/blob/master/src/utils/serial.cpp#L119 )

**Comment by Andrey1994** [comment]
Seems like you have root so you can set permissions directly and probably for you it will do the trick. Let me know about results but it looks like its not gonna work at least wo su.
There is relevant discussion in slack, feel free to join. I am closing this issue
